# Site settings
title: Front End Playground
email: zmeng@seas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
 "Front End Playground - tutorials, code + demo"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anniezmeng.com" # the base hostname & protocol for your site
github_username:  anniemeng

# Build settings
markdown: kramdown

# SASS settings
sass:
  style: compressed